name: release

on:
  release:
    types: [created]

jobs:
  release-windows:
    name: release windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "replace version"
      run: |
        VERSION=$(cat stable.txt)
        sed -i -e "s/{{VERSION}}/$VERSION/g" pkg/version/version.go
    - uses: wangyoucao577/go-release-action@v1.30
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        compress_assets: false
        md5sum: false
        sha256sum: true
        binary_name: not_coreshots
        asset_name: coreshots